services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.4-fpm
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD:  myModel01User
      MYSQL_DATABASE: myModel01_db
      MYSQL_USER: myModel01User
      MYSQL_PASSWORD: myModel01User
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST : db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: myModel01User
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: